<a href="https://colab.research.google.com/github/sparshap95-tech/ML-Engineering/blob/main/LogisticRegression_py.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
"""
Logistic Regression - Classification Example

This example covers:
1. Loading a dataset
2. Train-test split
3. Feature scaling
4. Training Logistic Regression
5. Class prediction
6. Probability prediction
7. Evaluation metrics
8. Confusion matrix
9. Coefficients and intercept
10. Regularization
"""

# ---------------------------------------------------------
# 1. Import libraries
# ---------------------------------------------------------

from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    classification_report,
    roc_auc_score
)


# ---------------------------------------------------------
# 2. Load dataset
# ---------------------------------------------------------

data = load_breast_cancer()

X = data.data       # Features
y = data.target     # Target

print("Dataset shape:", X.shape)
print("Target classes:", data.target_names)


# ---------------------------------------------------------
# 3. Split dataset into training and testing sets
# ---------------------------------------------------------

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

print("\nTraining samples:", X_train.shape[0])
print("Testing samples:", X_test.shape[0])


# ---------------------------------------------------------
# 4. Feature Scaling
# ---------------------------------------------------------

# Logistic Regression performs better when features
# are on a similar scale, especially with regularization.

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)


# ---------------------------------------------------------
# 5. Create Logistic Regression Model
# ---------------------------------------------------------

model = LogisticRegression(
    penalty="l2",      # L2 regularization
    C=1.0,             # inverse of regularization strength
    solver="lbfgs",
    max_iter=1000,
    random_state=42
)


# ---------------------------------------------------------
# 6. Train the model
# ---------------------------------------------------------

model.fit(X_train_scaled, y_train)


# ---------------------------------------------------------
# 7. Make class predictions
# ---------------------------------------------------------

y_pred = model.predict(X_test_scaled)

print("\nPredicted classes:")
print(y_pred[:10])


# ---------------------------------------------------------
# 8. Predict probabilities
# ---------------------------------------------------------

y_prob = model.predict_proba(X_test_scaled)

print("\nFirst 5 probability predictions:")
print(y_prob[:5])

# Probability of the positive class
positive_class_prob = y_prob[:, 1]


# ---------------------------------------------------------
# 9. Evaluate the model
# ---------------------------------------------------------

accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)
roc_auc = roc_auc_score(y_test, positive_class_prob)

print("\nMODEL EVALUATION")
print("-------------------------")
print("Accuracy :", accuracy)
print("Precision:", precision)
print("Recall   :", recall)
print("F1 Score :", f1)
print("ROC-AUC  :", roc_auc)


# ---------------------------------------------------------
# 10. Confusion Matrix
# ---------------------------------------------------------

cm = confusion_matrix(y_test, y_pred)

print("\nConfusion Matrix:")
print(cm)

# Format:
#
# [[TN FP]
#  [FN TP]]


# ---------------------------------------------------------
# 11. Classification Report
# ---------------------------------------------------------

print("\nClassification Report:")
print(
    classification_report(
        y_test,
        y_pred,
        target_names=data.target_names
    )
)


# ---------------------------------------------------------
# 12. Learned coefficients
# ---------------------------------------------------------

print("\nModel coefficients:")
print(model.coef_)

print("\nModel intercept:")
print(model.intercept_)


# ---------------------------------------------------------
# 13. Understand one prediction manually
# ---------------------------------------------------------

sample = X_test_scaled[0].reshape(1, -1)

sample_probability = model.predict_proba(sample)

sample_prediction = model.predict(sample)

print("\nSINGLE SAMPLE PREDICTION")
print("-------------------------")
print("Probability:", sample_probability)
print("Predicted class:", sample_prediction[0])
print("Actual class:", y_test[0])


# ---------------------------------------------------------
# 14. Custom threshold example
# ---------------------------------------------------------

threshold = 0.40

custom_predictions = (
    positive_class_prob >= threshold
).astype(int)

print("\nCustom threshold:", threshold)

print(
    "F1 with custom threshold:",
    f1_score(y_test, custom_predictions)
)


# ---------------------------------------------------------
# 15. Compare regularization strength
# ---------------------------------------------------------

print("\nREGULARIZATION COMPARISON")

for c_value in [0.01, 0.1, 1, 10, 100]:

    temp_model = LogisticRegression(
        C=c_value,
        penalty="l2",
        solver="lbfgs",
        max_iter=1000
    )

    temp_model.fit(X_train_scaled, y_train)

    temp_predictions = temp_model.predict(X_test_scaled)

    temp_accuracy = accuracy_score(
        y_test,
        temp_predictions
    )

    print(
        f"C={c_value:<6} Accuracy={temp_accuracy:.4f}"
    )

Dataset shape: (569, 30)
Target classes: ['malignant' 'benign']

Training samples: 455
Testing samples: 114

Predicted classes:
[0 1 0 1 0 1 1 0 0 0]

First 5 probability predictions:
[[9.99999941e-01 5.88824186e-08]
 [1.13351672e-05 9.99988665e-01]
 [9.93589175e-01 6.41082462e-03]
 [4.66491463e-01 5.33508537e-01]
 [9.99999999e-01 6.52500097e-10]]

MODEL EVALUATION
-------------------------
Accuracy : 0.9824561403508771
Precision: 0.9861111111111112
Recall   : 0.9861111111111112
F1 Score : 0.9861111111111112
ROC-AUC  : 0.9953703703703703

Confusion Matrix:
[[41  1]
 [ 1 71]]

Classification Report:
              precision    recall  f1-score   support

   malignant       0.98      0.98      0.98        42
      benign       0.99      0.99      0.99        72

    accuracy                           0.98       114
   macro avg       0.98      0.98      0.98       114
weighted avg       0.98      0.98      0.98       114


Model coefficients:
[[-0.51147901 -0.55269775 -0.47629789 -0.54105